### ISSUE TITLE
Please contribute some text to https://galene.org

### ISSUE THREAD

**Issue by jech** [YunoHost-Apps/galene_ynh#24]
### Describe the bug

There's no mention of this package on https://galene.org

### Context

I'm the upstream author of Galène.  I'd like to add some text to the https://galene.org web page that describes this package and links to it.  However, I don't use Yunohost myself, so I'm not sure what to write.  I'd like a two or three sentence description of 
Yunohost and a link that is likely to be useful both to users who don't use Yunohost yet and those who already do.

### Steps to reproduce

* Point your favourite browser at https://galene.org
* read the page
* notice there is no mention of Yunohost.

### Logs

While performing the actions above, write down the lack of mentions of Yunohost on a piece of paper.

**Comment by lapineige** [comment]
Hello,

For my part, as said [here](https://linuxfr.org/news/galene-un-serveur-de-videoconference-libre#comment-1837285), I was waiting for the package to be more stable to write something about it - because I don't want to create false hope by giving some attention on a package that was not complete and stable enough (and that could also give some bad reputation to Galène).
Now the package is much more complete, but for now I (and others) still have this issue #10, which might be a common issue, so I think it's too early to advertise it.

What do you think @ericgaspar ?

**Comment by jech** [comment]
> I was waiting for the package to be more stable to write something about it

It's up to you, of course.  The offer remains open.

**Comment by lapineige** [comment]
If we want to contribute, where should we submit the text ?

**Comment by jech** [comment]
Please send it by mail to <jch@irif.fr>.

**Comment by lapineige** [comment]
I think I'll do it after #20 is merged :)

@ericgaspar would you like to review it ?

**Comment by jech** [comment]
I've added a link to https://galene.org.  Closing.
