### ISSUE TITLE
Port 1194 is not reachable from outside in IPv6.

### ISSUE THREAD

**Issue by guizmoau** [YunoHost-Apps/galene_ynh#84]
### Describe the bug

Even with correct configuration of port, diagnosis page claim that port 1194 is not reachable from outside in IPV6

### Context

    Hardware: VPS
    YunoHost version: 4.3.6.3
    I have access to my server: ssh & webadmin
    Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
    Using, or trying to install package version/branch: 0.5.3

### Steps to reproduce

- install app
- configure port in VPS
- run diagnosis page

### Expected behavior

The port is configured open for IPV6 so it shall not be an error

**Comment by ericgaspar** [comment]
If I recall correctly the built-in TURN server dosn't work with IPV6...

**Comment by guizmoau** [comment]
Can this be solved somehow somewhere ?

**Comment by ericgaspar** [comment]
This seems to be an upstream limitation... @jech

There is this [galene+turn](https://github.com/YunoHost-Apps/galene_ynh/tree/galene+turn) branch which installs Coturn alongside Galène (this will install Galène 0.4.2) 

Or install Galène from the master branch and [coturn_ynh](https://github.com/YunoHost-Apps/coturn_ynh)
and follow the README instructions https://github.com/YunoHost-Apps/galene_ynh#using-your-own-turn-server

**Comment by jech** [comment]
> If I recall correctly the built-in TURN server doesn't work with IPV6...

Right.

> Can this be solved somehow somewhere ?

Somebody needs to implement [RFC 8656](https://www.rfc-editor.org/rfc/rfc8656) in [pion/turn](https://github.com/pion/turn).

Note however that TURN is only needed in order to cross restrictive firewalls; if you're running in an IPv6-only environment, you most likely control your network, so Galene should work fine even without a TURN server.  If that's not the case, I second Eric's suggestion ­— install coturn somewhere and put an `ice-servers.json` file that points Galene at it.
